/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  devnet: {
    HabitTracker: {
      address:
        "0x1e051fe5f24e31e4a21e2b9bbaa78c7805dd17065a995a41715641e7e914b05",
      abi: [
        {
          type: "impl",
          name: "HabitTrackerImpl",
          interface_name: "contracts::habit_tracker::IHabitTracker",
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "struct",
          name: "contracts::habit_tracker::UserState",
          members: [
            {
              name: "deposit_balance",
              type: "core::integer::u256",
            },
            {
              name: "blocked_balance",
              type: "core::integer::u256",
            },
            {
              name: "claimable_balance",
              type: "core::integer::u256",
            },
            {
              name: "active_habit_count",
              type: "core::integer::u32",
            },
          ],
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "struct",
          name: "contracts::habit_tracker::Habit",
          members: [
            {
              name: "id",
              type: "core::integer::u32",
            },
            {
              name: "owner",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "text",
              type: "core::felt252",
            },
            {
              name: "created_at_epoch",
              type: "core::integer::u64",
            },
            {
              name: "archived",
              type: "core::bool",
            },
          ],
        },
        {
          type: "struct",
          name: "contracts::habit_tracker::DailyStatus",
          members: [
            {
              name: "funded",
              type: "core::bool",
            },
            {
              name: "checked",
              type: "core::bool",
            },
            {
              name: "settled",
              type: "core::bool",
            },
          ],
        },
        {
          type: "struct",
          name: "contracts::habit_tracker::VaultState",
          members: [
            {
              name: "total_assets",
              type: "core::integer::u256",
            },
            {
              name: "total_supply",
              type: "core::integer::u256",
            },
            {
              name: "total_staked",
              type: "core::integer::u256",
            },
            {
              name: "accumulated_rewards",
              type: "core::integer::u256",
            },
            {
              name: "exchange_rate",
              type: "core::integer::u256",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::habit_tracker::IHabitTracker",
          items: [
            {
              type: "function",
              name: "deposit",
              inputs: [
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "withdraw_from_deposit",
              inputs: [
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "create_habit",
              inputs: [
                {
                  name: "text",
                  type: "core::felt252",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u32",
                },
              ],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "archive_habit",
              inputs: [
                {
                  name: "habit_id",
                  type: "core::integer::u32",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "check_in",
              inputs: [
                {
                  name: "habit_id",
                  type: "core::integer::u32",
                },
                {
                  name: "epoch_id",
                  type: "core::integer::u64",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "prepare_day",
              inputs: [
                {
                  name: "epoch_id",
                  type: "core::integer::u64",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "settle",
              inputs: [
                {
                  name: "user",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "epoch_id",
                  type: "core::integer::u64",
                },
                {
                  name: "habit_id",
                  type: "core::integer::u32",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "settle_all",
              inputs: [
                {
                  name: "user",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "epoch_id",
                  type: "core::integer::u64",
                },
                {
                  name: "max_count",
                  type: "core::integer::u32",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "force_settle_all",
              inputs: [
                {
                  name: "user",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "epoch_id",
                  type: "core::integer::u64",
                },
                {
                  name: "max_count",
                  type: "core::integer::u32",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "claim",
              inputs: [
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "redeposit_from_claimable",
              inputs: [
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "sync_staking_rewards",
              inputs: [],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "stake_to_protocol",
              inputs: [
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "unstake_from_protocol",
              inputs: [
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_user_state",
              inputs: [
                {
                  name: "user",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "contracts::habit_tracker::UserState",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_habits",
              inputs: [
                {
                  name: "user",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::array::Array::<contracts::habit_tracker::Habit>",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_daily_status",
              inputs: [
                {
                  name: "user",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "epoch_id",
                  type: "core::integer::u64",
                },
                {
                  name: "habit_id",
                  type: "core::integer::u32",
                },
              ],
              outputs: [
                {
                  type: "contracts::habit_tracker::DailyStatus",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "epoch_now",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u64",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "treasury_address",
              inputs: [],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "stake_per_day",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_vault_state",
              inputs: [],
              outputs: [
                {
                  type: "contracts::habit_tracker::VaultState",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "accumulated_rewards",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "total_staked",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "treasury_addr",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "staking_contract_addr",
              type: "core::starknet::contract_address::ContractAddress",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::habit_tracker::HabitTracker::Deposited",
          kind: "struct",
          members: [
            {
              name: "user",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::habit_tracker::HabitTracker::Withdrew",
          kind: "struct",
          members: [
            {
              name: "user",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::habit_tracker::HabitTracker::HabitCreated",
          kind: "struct",
          members: [
            {
              name: "user",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "habit_id",
              type: "core::integer::u32",
              kind: "data",
            },
            {
              name: "text",
              type: "core::felt252",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::habit_tracker::HabitTracker::HabitArchived",
          kind: "struct",
          members: [
            {
              name: "user",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "habit_id",
              type: "core::integer::u32",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::habit_tracker::HabitTracker::Checked",
          kind: "struct",
          members: [
            {
              name: "user",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "habit_id",
              type: "core::integer::u32",
              kind: "data",
            },
            {
              name: "epoch_id",
              type: "core::integer::u64",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::habit_tracker::HabitTracker::Prepared",
          kind: "struct",
          members: [
            {
              name: "user",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "epoch_id",
              type: "core::integer::u64",
              kind: "data",
            },
            {
              name: "funded_count",
              type: "core::integer::u32",
              kind: "data",
            },
            {
              name: "insufficient_count",
              type: "core::integer::u32",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::habit_tracker::HabitTracker::SettledSuccess",
          kind: "struct",
          members: [
            {
              name: "user",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "habit_id",
              type: "core::integer::u32",
              kind: "data",
            },
            {
              name: "epoch_id",
              type: "core::integer::u64",
              kind: "data",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::habit_tracker::HabitTracker::SettledFail",
          kind: "struct",
          members: [
            {
              name: "user",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "habit_id",
              type: "core::integer::u32",
              kind: "data",
            },
            {
              name: "epoch_id",
              type: "core::integer::u64",
              kind: "data",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::habit_tracker::HabitTracker::Claimed",
          kind: "struct",
          members: [
            {
              name: "user",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::habit_tracker::HabitTracker::ReDeposited",
          kind: "struct",
          members: [
            {
              name: "user",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::habit_tracker::HabitTracker::StakedToProtocol",
          kind: "struct",
          members: [
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
            {
              name: "epoch",
              type: "core::integer::u64",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::habit_tracker::HabitTracker::UnstakedFromProtocol",
          kind: "struct",
          members: [
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
            {
              name: "epoch",
              type: "core::integer::u64",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::habit_tracker::HabitTracker::RewardsAccrued",
          kind: "struct",
          members: [
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
            {
              name: "new_total_assets",
              type: "core::integer::u256",
              kind: "data",
            },
            {
              name: "epoch",
              type: "core::integer::u64",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::habit_tracker::HabitTracker::Event",
          kind: "enum",
          variants: [
            {
              name: "Deposited",
              type: "contracts::habit_tracker::HabitTracker::Deposited",
              kind: "nested",
            },
            {
              name: "Withdrew",
              type: "contracts::habit_tracker::HabitTracker::Withdrew",
              kind: "nested",
            },
            {
              name: "HabitCreated",
              type: "contracts::habit_tracker::HabitTracker::HabitCreated",
              kind: "nested",
            },
            {
              name: "HabitArchived",
              type: "contracts::habit_tracker::HabitTracker::HabitArchived",
              kind: "nested",
            },
            {
              name: "Checked",
              type: "contracts::habit_tracker::HabitTracker::Checked",
              kind: "nested",
            },
            {
              name: "Prepared",
              type: "contracts::habit_tracker::HabitTracker::Prepared",
              kind: "nested",
            },
            {
              name: "SettledSuccess",
              type: "contracts::habit_tracker::HabitTracker::SettledSuccess",
              kind: "nested",
            },
            {
              name: "SettledFail",
              type: "contracts::habit_tracker::HabitTracker::SettledFail",
              kind: "nested",
            },
            {
              name: "Claimed",
              type: "contracts::habit_tracker::HabitTracker::Claimed",
              kind: "nested",
            },
            {
              name: "ReDeposited",
              type: "contracts::habit_tracker::HabitTracker::ReDeposited",
              kind: "nested",
            },
            {
              name: "StakedToProtocol",
              type: "contracts::habit_tracker::HabitTracker::StakedToProtocol",
              kind: "nested",
            },
            {
              name: "UnstakedFromProtocol",
              type: "contracts::habit_tracker::HabitTracker::UnstakedFromProtocol",
              kind: "nested",
            },
            {
              name: "RewardsAccrued",
              type: "contracts::habit_tracker::HabitTracker::RewardsAccrued",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x6baf1b90947d225afd01fa7d285a573d47bae566705f8f165aa0dd184cd6ce1",
    },
  },
  sepolia: {
    HabitTracker: {
      address:
        "0x357f2cfa7b8b688dd51b2833bcc8fa433b90a0a43ec5b9594783fa514ef0e71",
      abi: [
        {
          type: "impl",
          name: "HabitTrackerImpl",
          interface_name: "contracts::habit_tracker::IHabitTracker",
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "struct",
          name: "contracts::habit_tracker::UserState",
          members: [
            {
              name: "deposit_balance",
              type: "core::integer::u256",
            },
            {
              name: "blocked_balance",
              type: "core::integer::u256",
            },
            {
              name: "claimable_balance",
              type: "core::integer::u256",
            },
            {
              name: "active_habit_count",
              type: "core::integer::u32",
            },
          ],
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "struct",
          name: "contracts::habit_tracker::Habit",
          members: [
            {
              name: "id",
              type: "core::integer::u32",
            },
            {
              name: "owner",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "text",
              type: "core::felt252",
            },
            {
              name: "created_at_epoch",
              type: "core::integer::u64",
            },
            {
              name: "archived",
              type: "core::bool",
            },
          ],
        },
        {
          type: "struct",
          name: "contracts::habit_tracker::DailyStatus",
          members: [
            {
              name: "funded",
              type: "core::bool",
            },
            {
              name: "checked",
              type: "core::bool",
            },
            {
              name: "settled",
              type: "core::bool",
            },
          ],
        },
        {
          type: "struct",
          name: "contracts::habit_tracker::VaultState",
          members: [
            {
              name: "total_assets",
              type: "core::integer::u256",
            },
            {
              name: "total_supply",
              type: "core::integer::u256",
            },
            {
              name: "total_staked",
              type: "core::integer::u256",
            },
            {
              name: "accumulated_rewards",
              type: "core::integer::u256",
            },
            {
              name: "exchange_rate",
              type: "core::integer::u256",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::habit_tracker::IHabitTracker",
          items: [
            {
              type: "function",
              name: "deposit",
              inputs: [
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "withdraw_from_deposit",
              inputs: [
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "create_habit",
              inputs: [
                {
                  name: "text",
                  type: "core::felt252",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u32",
                },
              ],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "archive_habit",
              inputs: [
                {
                  name: "habit_id",
                  type: "core::integer::u32",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "check_in",
              inputs: [
                {
                  name: "habit_id",
                  type: "core::integer::u32",
                },
                {
                  name: "epoch_id",
                  type: "core::integer::u64",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "prepare_day",
              inputs: [
                {
                  name: "epoch_id",
                  type: "core::integer::u64",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "settle",
              inputs: [
                {
                  name: "user",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "epoch_id",
                  type: "core::integer::u64",
                },
                {
                  name: "habit_id",
                  type: "core::integer::u32",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "settle_all",
              inputs: [
                {
                  name: "user",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "epoch_id",
                  type: "core::integer::u64",
                },
                {
                  name: "max_count",
                  type: "core::integer::u32",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "force_settle_all",
              inputs: [
                {
                  name: "user",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "epoch_id",
                  type: "core::integer::u64",
                },
                {
                  name: "max_count",
                  type: "core::integer::u32",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "claim",
              inputs: [
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "redeposit_from_claimable",
              inputs: [
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "sync_staking_rewards",
              inputs: [],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "stake_to_protocol",
              inputs: [
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "unstake_from_protocol",
              inputs: [
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_user_state",
              inputs: [
                {
                  name: "user",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "contracts::habit_tracker::UserState",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_habits",
              inputs: [
                {
                  name: "user",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::array::Array::<contracts::habit_tracker::Habit>",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_daily_status",
              inputs: [
                {
                  name: "user",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "epoch_id",
                  type: "core::integer::u64",
                },
                {
                  name: "habit_id",
                  type: "core::integer::u32",
                },
              ],
              outputs: [
                {
                  type: "contracts::habit_tracker::DailyStatus",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "epoch_now",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u64",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "treasury_address",
              inputs: [],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "stake_per_day",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_vault_state",
              inputs: [],
              outputs: [
                {
                  type: "contracts::habit_tracker::VaultState",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "accumulated_rewards",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "total_staked",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "treasury_addr",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "staking_contract_addr",
              type: "core::starknet::contract_address::ContractAddress",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::habit_tracker::HabitTracker::Deposited",
          kind: "struct",
          members: [
            {
              name: "user",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::habit_tracker::HabitTracker::Withdrew",
          kind: "struct",
          members: [
            {
              name: "user",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::habit_tracker::HabitTracker::HabitCreated",
          kind: "struct",
          members: [
            {
              name: "user",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "habit_id",
              type: "core::integer::u32",
              kind: "data",
            },
            {
              name: "text",
              type: "core::felt252",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::habit_tracker::HabitTracker::HabitArchived",
          kind: "struct",
          members: [
            {
              name: "user",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "habit_id",
              type: "core::integer::u32",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::habit_tracker::HabitTracker::Checked",
          kind: "struct",
          members: [
            {
              name: "user",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "habit_id",
              type: "core::integer::u32",
              kind: "data",
            },
            {
              name: "epoch_id",
              type: "core::integer::u64",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::habit_tracker::HabitTracker::Prepared",
          kind: "struct",
          members: [
            {
              name: "user",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "epoch_id",
              type: "core::integer::u64",
              kind: "data",
            },
            {
              name: "funded_count",
              type: "core::integer::u32",
              kind: "data",
            },
            {
              name: "insufficient_count",
              type: "core::integer::u32",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::habit_tracker::HabitTracker::SettledSuccess",
          kind: "struct",
          members: [
            {
              name: "user",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "habit_id",
              type: "core::integer::u32",
              kind: "data",
            },
            {
              name: "epoch_id",
              type: "core::integer::u64",
              kind: "data",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::habit_tracker::HabitTracker::SettledFail",
          kind: "struct",
          members: [
            {
              name: "user",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "habit_id",
              type: "core::integer::u32",
              kind: "data",
            },
            {
              name: "epoch_id",
              type: "core::integer::u64",
              kind: "data",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::habit_tracker::HabitTracker::Claimed",
          kind: "struct",
          members: [
            {
              name: "user",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::habit_tracker::HabitTracker::ReDeposited",
          kind: "struct",
          members: [
            {
              name: "user",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::habit_tracker::HabitTracker::StakedToProtocol",
          kind: "struct",
          members: [
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
            {
              name: "epoch",
              type: "core::integer::u64",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::habit_tracker::HabitTracker::UnstakedFromProtocol",
          kind: "struct",
          members: [
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
            {
              name: "epoch",
              type: "core::integer::u64",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::habit_tracker::HabitTracker::RewardsAccrued",
          kind: "struct",
          members: [
            {
              name: "amount",
              type: "core::integer::u256",
              kind: "data",
            },
            {
              name: "new_total_assets",
              type: "core::integer::u256",
              kind: "data",
            },
            {
              name: "epoch",
              type: "core::integer::u64",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::habit_tracker::HabitTracker::Event",
          kind: "enum",
          variants: [
            {
              name: "Deposited",
              type: "contracts::habit_tracker::HabitTracker::Deposited",
              kind: "nested",
            },
            {
              name: "Withdrew",
              type: "contracts::habit_tracker::HabitTracker::Withdrew",
              kind: "nested",
            },
            {
              name: "HabitCreated",
              type: "contracts::habit_tracker::HabitTracker::HabitCreated",
              kind: "nested",
            },
            {
              name: "HabitArchived",
              type: "contracts::habit_tracker::HabitTracker::HabitArchived",
              kind: "nested",
            },
            {
              name: "Checked",
              type: "contracts::habit_tracker::HabitTracker::Checked",
              kind: "nested",
            },
            {
              name: "Prepared",
              type: "contracts::habit_tracker::HabitTracker::Prepared",
              kind: "nested",
            },
            {
              name: "SettledSuccess",
              type: "contracts::habit_tracker::HabitTracker::SettledSuccess",
              kind: "nested",
            },
            {
              name: "SettledFail",
              type: "contracts::habit_tracker::HabitTracker::SettledFail",
              kind: "nested",
            },
            {
              name: "Claimed",
              type: "contracts::habit_tracker::HabitTracker::Claimed",
              kind: "nested",
            },
            {
              name: "ReDeposited",
              type: "contracts::habit_tracker::HabitTracker::ReDeposited",
              kind: "nested",
            },
            {
              name: "StakedToProtocol",
              type: "contracts::habit_tracker::HabitTracker::StakedToProtocol",
              kind: "nested",
            },
            {
              name: "UnstakedFromProtocol",
              type: "contracts::habit_tracker::HabitTracker::UnstakedFromProtocol",
              kind: "nested",
            },
            {
              name: "RewardsAccrued",
              type: "contracts::habit_tracker::HabitTracker::RewardsAccrued",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x2a5604b70988ce1c78acbf3fee29ea418f2359be5bf755201ce94b0e1002ee9",
    },
  },
} as const;

export default deployedContracts;
