name: Deploy to GitHub Pages

on:
  # Disabled: Dynamic routes with empty generateStaticParams() don't work with static export
  # Next.js requires pre-rendered paths for static export, but our block explorer
  # uses purely client-side dynamic routes that can't be pre-generated
  # See: https://nextjs.org/docs/app/building-your-application/deploying/static-exports
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Next.js app
        run: |
          cd packages/nextjs
          yarn build
        env:
          NEXT_PUBLIC_BASE_PATH: /${{ github.event.repository.name }}
          NODE_ENV: production

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./packages/nextjs/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

